[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'npx tsx backend/server.ts'

[variables]
NODE_ENV = 'production'
PORT = '3001'
HOST = '0.0.0.0'