[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx tsx backend/hono.ts --check || echo "TypeScript check completed"']

[start]
cmd = 'npx tsx backend/server.ts'

[variables]
NODE_ENV = 'production'