name: Build iOS App (Fixed)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'app.json'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build iOS without auto-submit
        run: |
          echo "Starting iOS build without auto-submit..."
          npx eas-cli build --platform ios --profile production --non-interactive --clear-cache
        env:
          EAS_NO_VCS: 1
          EXPO_NO_CAPABILITY_SYNC: 1
          EAS_BUILD_AUTOCOMMIT: 1

      - name: Submit to App Store (if build succeeds)
        run: |
          echo "Submitting to App Store..."
          npx eas-cli submit --platform ios --profile production --non-interactive --latest
        env:
          EAS_NO_VCS: 1