name: Build iOS App

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - 'components/**'
      - 'app.json'
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Configure EAS credentials
        run: |
          echo "Setting up EAS credentials for non-interactive build..."
          npx eas-cli credentials:configure --platform ios --profile production --non-interactive || true

      - name: Build iOS
        run: |
          echo "Starting iOS build..."
          npx eas-cli build --platform ios --profile production --non-interactive --clear-cache
        env:
          EAS_NO_VCS: 1