name: EAS Build and Init

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Initialize EAS
        run: npx eas-cli init --id 4aa81beb-ebf2-4e52-85bd-a04abd142c5e --non-interactive

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add app.json
          git commit -m "EAS init from Actions" || echo "No changes"
          git push

      - name: Build iOS
        run: npx eas-cli build --platform ios --profile production --auto-submit --non-interactive
